version: '3.8'
services:
  sills:
    build: .
    ports:
      - "56666:56666"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONPATH=/app
    restart: unless-stopped
    volumes:
      - sills_data:/app/instance
      - sills_uploads:/app/uploads
      - sills_static_uploads:/app/static/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:56666/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  sills_data:
  sills_uploads:
  sills_static_uploads: 